apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "3x-ui.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "3x-ui.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "3x-ui.name" . }}
    spec:
      containers:
        - name: 3x-ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: XRAY_VMESS_AEAD_FORCED
              value: "{{ .Values.env.XRAY_VMESS_AEAD_FORCED }}"
            - name: XUI_ENABLE_FAIL2BAN
              value: "{{ .Values.env.XUI_ENABLE_FAIL2BAN }}"
          volumeMounts:
            - name: db
              mountPath: {{ .Values.persistence.dbPath }}
            - name: cert
              mountPath: {{ .Values.persistence.certPath }}
      volumes:
        - name: db
          emptyDir: {}
        - name: cert
          emptyDir: {}
