{{- if .Values.xray.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "xui.fullname" . }}-tcp
  labels:
    {{- include "xui.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`{{ .Values.hostname }}`)
      services:
        - name: {{ include "xui.fullname" . }}
          port: {{ .Values.xray.port }}
  tls:
    passthrough: true
{{- end }}
