apiVersion: v1
kind: Service
metadata:
  name: {{ include "xui.fullname" . }}
  labels:
    {{- include "xui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.xray.enabled }}
    - port: {{ .Values.xray.port }}
      targetPort: xray
      protocol: TCP
      name: xray
    {{- end }}
  selector:
    {{- include "xui.selectorLabels" . | nindent 4 }}
